version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-vscode-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1n33cn3joi4d0"
s3_prefix = "sam-vscode-app"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

